### ISSUE TITLE
Please delete unused obsolete branches

### ISSUE THREAD

**Issue by alexei-31** [fingolfin/git-remote-hg#13]
Please delete unused obsolete branches from you repository. It is important to simplify the fork and learning code newcomers.

* __misc__ — all commits in master added by cherry pick
* __submodules__ — commit added in master by cherry pick
* __test__ — obsolete detection of hg 3.2
* __fix-hg-3.2__ — old branch which merged into master

These branches have been cloned in the forks @razaraz and @strachu so they can refer to in one of these repositories, if it is required to merge or anything else.

**Comment by fingolfin** [comment]
Done.

**Comment by alexei-31** [comment]
Thanks.
I added the notifications (link to this repository) to clarify in issues of  @felipec, which closed in the pull request:
* felipec:#25 – submodules
* felipec:#28 – fix-hg-3.2
I can remove or edit those posts, if it will seem inappropriate.

**Comment by alexei-31** [comment]
Details:
* __fix-hg-3.2__ fully merged into commit [`e716a9e1`](https://github.com/fingolfin/git-remote-hg/commit/e716a9e1a9e460a45663694ba4e9e8894a8452b2)
* __submodules__ by cherry pick moved into commit [`c3a4adc8`](https://github.com/fingolfin/git-remote-hg/commit/c3a4adc8689f4cfa46fa3c74afad9a73bad9c75e)
* __test__ – 2 of 3 commits (e4aeae6d4b5d9717f2f23c11ab662f45d23bfe79 and e71a8963af2bb00b38cec7bc084bb55b0788676c) joined into [`29a0d8a0`](https://github.com/fingolfin/git-remote-hg/commit/29a0d8a0e308c50e4da8cf4e8fe3348d420818ab) (only f20dbc33c36fc7a781d5b12ee4e7067ce907fce8 was dropped)
* __misc__ – all six commits rebased (in other order) between [`e716a9e1`](https://github.com/fingolfin/git-remote-hg/commit/e716a9e1a9e460a45663694ba4e9e8894a8452b2) and 13b20f8380bf73812f5f131169fac672e7647118 
(but 4dba11ca591c01579546f540a81a9d72ddf0f80b has some changes from original)
