### ISSUE TITLE
Filenames in Git repo have \ as file separator on Windows

### ISSUE THREAD

**Issue by msc-** [fingolfin/git-remote-hg#4]
Doing

```bash
git clone hg::http://hg.libsdl.org/SDL
```

in Git Bash on Windows 10 I get a lot of messages from the `git checkout` phase like

```
error: unable to create file VisualC\SDL.sln (No such file or directory)
```

Note this is *not* the filename > 260 characters issue that is reported in many, many, hits when searching for this error. The filename above is short and just to be sure I put the clone in C:/SDL.

I am sure this is caused by the '\' in the filename. Why would the separator have been changed? Could it have something to do with my using the Windows version of Python 2.7? Should I perhaps use Cygwin instead? Has anyone else seen this problem?

 I have cloned this same repo on a Mac using git-remote-hg without issue.

**Comment by fingolfin** [comment]
Sorry, I have no idea, I don't know much about Windows. But yeah, it could be your shell automatically converting slashes to backslahes... Does it help to put the string into (single) quotes?

All in all, though I am afraid there is little to nothing I can do to help you with this.

**Comment by nathanielcook** [comment]
I am also running into this. The git-remote-hg script works fine on OSX but on Windows I get a lot of "No such file or directory" errors during checkout. @msc- If you clone on the Mac and then move that repo to Windows does it still give you errors during checkout?

**Comment by msc-** [comment]
I copied the repo I cloned on my Mac to Windows then did
```bash
$ cd <repo>
$ git checkout upstream_master # branch linked to remote hg repo
$ rm -rf *  # remove all files except for .git
$ git reset --hard HEAD  # Restore with Windows line endings
$ git config core.filemode false # Ignore differing file modes
$ git status
On branch upstream_master
Your branch is up-to-date with 'upstream/master'.
nothing to commit, working directory clean
$ git pull
searching for changes
adding changesets
adding manifests
adding file changes
added 10 changesets with 58 changes to 52 files
From hg::http://hg.libsdl.org/SDL
   778c73e..3160f54  master     -> upstream/master
   778c73e..3160f54  branches/default -> upstream/branches/default
Updating 778c73e..3160f54
error: The following untracked working tree files would be overwritten by merge:
... a list of every file in the repo printed using Unix-style paths.
...
Please move or remove them before you can merge.
Aborting
```

I am using Git for Windows (i.e. the Git Bash shell) and Python for Windows. Hg appears to be Python as well. `git-remote-hg` uses os.join.path() when creating files which will make Windows style paths. 

I know nothing of the internals of `git` or the interface between `git` and `git-remote-hg` and so have so far been unable to come up with a theory which accounts for both of these problems.

**Comment by alexei-31** [comment]
It solved in pull request #6 
Please, close this issue or join with that pull request.

**Comment by fingolfin** [comment]
PR #6 has been merged. @msc- does this fix the problem for you (at least when it comes to cloning / pulling)?

As I understand it, push still needs to be fixed.

**Comment by msc-** [comment]
With PR #6, clones and pulls work fine.  I did have one scare as a pull attempt, in a repo in which I had previously tried a pull using the broken git-remote-hg, gave me `ERROR: Abandoned transaction found.` Fortunately after deleting my clone and cloning again from my git remote (that was pushed from a git-remote-hg clone done on OS X), `git pull` worked.

I can't test push as I do not have write permission to the repo I am using.

**Comment by alexei-31** [comment]
Thank you very much for taking the time to check. Could you make a push in the [local repository](https://www.texniq.de/en/web-engineering-i/create-local-git-repo-and-push-to-github) or in [bitbucket.org](https://bitbucket.org/) (closed supports free repository) or in [github.com](https://github.com/new) (if the code is open) to check only. Then you can delete the repository after test, but we can finally close this issue.

**Comment by nathanielcook** [comment]
I think this issue can be closed now. The remaining problems on Windows are elsewhere.
