### ISSUE TITLE
Pulling from resulting hg repo gives erroneous commit hashes

### ISSUE THREAD

**Issue by jmpalacios** [fingolfin/git-remote-hg#5]
Hi!

I'm using Git and Mercurial as installed by MacPorts on a Mac, and I can use this git-remote-hg fork to push to a Mercurial remote just fine. But the problem I'm facing is that when I clone the resulting repo from some other location with git I get back different SHA1 commit identifiers, which needless to say makes the clone completely unusable.

First off, my environment:

```
 -> sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F1021
-> git --version
git version 2.6.2
-> hg --version
Mercurial Distributed SCM (version 3.6.1)
(...)
 -> head $(which hg)
#!/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
(...)
-> /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python --version
Python 2.7.10
```

And now some simple steps to reproduce the problem with on-the-fly test repos & clones:

```
-> hg init hg-remote
-> git init git-clone-1
Initialized empty Git repository in /private/tmp/git-clone-1/.git/
-> cd git-clone-1/
-> echo hi > hi
-> git add hi 
-> git ci -m "Adding test file."
[master (root-commit) 7c1c782] Adding test file.
 1 file changed, 1 insertion(+)
 create mode 100644 hi
-> git --no-pager log
commit 7c1c7828125982190891a21b61cebc1add51bf28 (HEAD -> master)
Author: Juan Manuel Palacios <jmpalacios@gmail.com>
Date:   Mon Nov 16 23:20:36 2015 -0430

    Adding test file.
-> git remote add hg-remote hg::../hg-remote
-> git push hg-remote master 
committing files:
hi
committing manifest
committing changelog
To hg::../hg-remote
 * [new branch]      master -> master
-> cd ../
-> git clone hg::hg-remote git-clone-2
Cloning into 'git-clone-2'...
Checking connectivity... done.
-> cd git-clone-2
-> git --no-pager log
commit fa283ed2a80ab60b090d761ac839c98eca2bf128 (HEAD -> master, origin/master, origin/branches/default, origin/HEAD, refs/hg/origin/branches/default, refs/hg/origin/bookmarks/master)
Author: Juan Manuel Palacios <jmpalacios@gmail.com>
Date:   Mon Nov 16 23:40:36 2015 -0410

    Adding test file.
```

As you can see, the commit identifier is completely different. I've tracked, I think, the culprit to the timezone in the resulting commit in the hg-remote repo. You can see that in the original repo, git-clone-1, the timezone is -0430, but in git-clone-2 it's 0410. In the hg-remote intermediary it's yet another one:

```
 -> hg -R ../hg-remote --pager never log
changeset:   0:808283b17f4f
tag:         tip
user:        Juan Manuel Palacios <jmpalacios@gmail.com>
date:        Tue Nov 17 00:00:36 2015 -0350
files:       hi
description:
Adding test file.
```

Leading me to believe the error is in creating the Mercurial commits that get pushed to the Mercurial remote, since that -0350 offset is definitely incorrect; also, the -10 minutes offset bears resemblance to the +10 minutes offset in the commit in git-clone-2 (I've read about hg timezones having negative offsets and git timezones positive).

On the other hand, a commit created directly in hg definitely has the correct timezone:

```
 -> cd ../
-> hg init tz-test
-> cd tz-test/
-> echo hi > hi
-> hg add hi 
adding hi
-> hg ci -m "Adding test file."
committing files:
hi
committing manifest
committing changelog
committed changeset 0:434010fde109
-> hg --pager never log
changeset:   0:434010fde109
tag:         tip
user:        Juan Manuel Palacios <jmpalacios@gmail.com>
date:        Mon Nov 16 23:45:18 2015 -0430
files:       hi
description:
Adding test file.
```

So, since the problem seems to be in the hg commits, git-cloning the intermediary hg remote from any other system, say Linux, produces identically erroneous results, which I've verified with a real-life repo I'm trying to bridge between Git & Mercurial across my home Mac and an office Linux server.

Lastly, git commits in both clones having the same tree contents and patch Id's lends more weight to the hypothesis of the commit contents themselves being OK, and the info around them being what introduces the problems:

```
-> cd ../git-clone-1
-> git ls-tree 7c1c7828125982190891a21b61cebc1add51bf28
100644 blob 45b983be36b73c0788dc9cbcb76cbb80fc7bb057    hi
-> git show | git patch-id
eaca4303a892836b7e887cffdb6ba100b78023fa 7c1c7828125982190891a21b61cebc1add51bf28
-> cd ../git-clone-2
-> git ls-tree fa283ed2a80ab60b090d761ac839c98eca2bf128
100644 blob 45b983be36b73c0788dc9cbcb76cbb80fc7bb057    hi
-> git show | git patch-id
eaca4303a892836b7e887cffdb6ba100b78023fa fa283ed2a80ab60b090d761ac839c98eca2bf128
```

Thanks for any help in advance, and let me know if there's any more info from my system & tools that would help you spot the problem!

**Comment by fingolfin** [comment]
This patch fixed it in my tests (basically, I took your test code, and used `--date` to force a negative time zone offset in the git commit). Please test if this really solves the issue for you; if not, feel free to reopen.
